import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Lavishly_Yours, Montserrat, Orbitron, Ms_Madi, Great_Vibes } from "next/font/google";
import "./globals.css";

const lavishlyYours = Lavishly_Yours({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: "--font-lavishly" 
});

const greatVibes = Great_Vibes({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: "--font-great-vibes" 
});

const msMadi = Ms_Madi({ 
  subsets: ["latin"], 
  weight: "400", 
  variable: "--font-ms-madi" 
});

const montserrat = Montserrat({ 
  subsets: ["latin"], 
  variable: "--font-montserrat" 
});

const orbitron = Orbitron({ 
  subsets: ["latin"], 
  variable: "--font-orbitron" 
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lavishlyYours.variable} ${montserrat.variable} ${orbitron.variable} ${greatVibes.variable} ${msMadi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
